apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
images:
  - name: demo-webapi
    newName: quay.io/YOUR_ORG/demo-webapi
    newTag: latest
