apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-webapi-prod
resources:
  - ../../base
  - connectivity-link.yaml
commonLabels:
  app.kubernetes.io/part-of: demo-webapi
  app.kubernetes.io/environment: prod
images:
  - name: demo-webapi
    newName: quay.io/rh-ee-egevorky/demo-webapi
    newTag: 0.1.0
