apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: demo-webapi-prod-promote-
spec:
  pipelineRef:
    name: demo-webapi-promote
  params:
    - name: gitOpsRepoUrl
      value: https://github.com/arencloud/demo-webapi-gitops.git
    - name: gitOpsRevision
      value: main
    - name: imageRepo
      value: quay.io/rh-ee-egevorky/demo-webapi
    - name: imageTag
      value: "0.1.0"
    - name: sourceEnvironment
      value: stage
    - name: targetEnvironment
      value: prod
  taskRunTemplate:
    serviceAccountName: pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: git-credentials
