// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/ping": {
            "get": {
                "description": "Returns a simple ping message and request headers",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "ping"
                ],
                "summary": "Ping endpoint",
                "responses": {
                    "200": {
                        "description": "Hello I am Ping",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/realms/ext/npwl-user/logout": {
            "get": {
                "description": "Returns a logout message and request headers",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Advanced Logout endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Extranet URL",
                        "name": "extranetUrl",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Hello I am advanced logged-out endpoint",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/realms/ext/protocol/cas/connect": {
            "get": {
                "description": "Returns a connect message and request headers",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Advanced Connect endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Extranet ID",
                        "name": "extranetId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "p param",
                        "name": "p",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Hello I am advanced ping",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "WebApp API",
	Description:      "This is a sample webapp server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
